apiVersion: v1
kind: Secret
metadata:
  name: stripe
type: Opaque
data:
  secretKey: c2tfdGVzdF81MVJqdTNHUE9heUNJUFdMY3Znck5rSXE3SGt3bnZMdjEwS0J5TUo2M3FmbWRkY2t6eTkyVkNwckJEYUlPeVlRZWN2OXVvS01pd0l6S2VOQkV4Zmd4aVlwSTAwZWxad01meEM=  # base64 de sk_test_tu_secreto_de_stripe
